### ISSUE TITLE
backspace broken in all gdbs

### ISSUE THREAD

**Issue by slightlyunconventional** [bootlin/toolchains-builder#13]
### Steps to reproduce:
1. Run aarch64-linux-gdb
2. Type "foo" followed by a backspace (or ctrl-H, or ctrl-U)

### Results:
Instead of rewinding the cursor and removing the previous character, each backspace appends a space to the cmdline.

### More information:
```
$ ldd <...>/aarch64--glibc--stable-2018.02-2/bin/aarch64-linux-gdb 
        linux-vdso.so.1 =>  (0x00007fffd6bff000)
        libdl.so.2 => /lib64/libdl.so.2 (0x0000003fe7e00000)
        libncurses.so.6 => <...>/aarch64--glibc--stable-2018.02-2/bin/../lib/libncurses.so.6 (0x00007fe757063000)
        libm.so.6 => /lib64/libm.so.6 (0x0000003fe8a00000)
        libexpat.so.1 => <...>/aarch64--glibc--stable-2018.02-2/bin/../lib/libexpat.so.1 (0x00007fe756e3b000)
        libc.so.6 => /lib64/libc.so.6 (0x0000003fe8200000)
        /lib64/ld-linux-x86-64.so.2 (0x0000003fe7a00000)
```

On Fedora 27, `LD_PRELOAD=/usr/lib64/libncurses.so.6.0 host/bin/x86_64-linux-gdb` works around the problem, indicating it's something inside the bundled libncurses.so.6. (RHEL 6 only provides ncurses 5.7, so this trick is unavailable there.)

### Affected releases:
- 2017.05 aarch64 glibc stable
- 2018.02 aarch64 glibc stable
- unknown microblaze toolchain
- unknown x86 toolchain

### Affected host distributions:
- RHEL 6.5
- Fedora 27

(Haven't tested others.)

**Comment by xyzzy42** [comment]
The toolchain x86-64-core-i7--glibc--bleeding-edge-2018.02-1 is affected by this.  Substituting the FC27 ncurses shared lib in place of the toolchain's bundled ncurses fixes the problem.

**Comment by slightlyunconventional** [comment]
I've posted an upstream Buildroot [patch](http://lists.busybox.net/pipermail/buildroot/2018-July/225596.html) to fix this problem.

**Comment by tpetazzoni** [comment]
This issue is fixed in the 2018.07-1 bleeding edge toolchains. However, it isn't fixed yet in the stable toolchains, which I need to rebuild.

**Comment by anatolyborodin** [comment]
Is it related to #30 ?

**Comment by tpetazzoni** [comment]
@anatolyborodin yes, absolutely. The fix we did back then with http://lists.busybox.net/pipermail/buildroot/2018-July/225596.html in fact does work well for all platforms, because not all systems have the terminfo database installed in /usr/share/terminfo/. I'm going to close this bug, and keep #30 open.
