### ISSUE TITLE
Build local toolchains

### ISSUE THREAD

**Issue by plauche** [bootlin/toolchains-builder#27]
Hi,

I'm attempting to build a new toolchain locally but am running into some issues. I modified the `armv7m.config` file and ran the command: `sudo ./build.sh armv7m--uclibc--cortexm3 test stable 2020-1-25`.

I ended up getting these errors:
```
cp: cannot stat '/home/vagrant/toolchains-builder/frags/armv7m--uclibc--cortexm3.config': No such file or directory
Uploading build log
The authenticity of host 'toolchains.bootlin.com (51.254.149.199)' can't be established.
RSA key fingerprint is SHA256:eQBz/dpQC+2zY8kNtJZZraH6lZgTR1LMju1Colf5IgI.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'toolchains.bootlin.com,51.254.149.199' (RSA) to the list of known hosts.
gitlabci@toolchains.bootlin.com: Permission denied (publickey).
gitlabci@toolchains.bootlin.com: Permission denied (publickey).
lost connection
Toolchain build failed, not going further
```
I'm not entirely sure what I've done wrong here.

**Comment by tpetazzoni** [comment]
As it is implemented today, the toolchain-builders logic is not really suited to easily build the toolchains yourself: here it tries to upload the resulting toolchains to the official toolchains.bootlin.com. If you need to build just one toolchain, you can do that with Buildroot directly: toolchain-builder is only here to automate the process of building/testing/uploading/publishing a large number of toolchains.

**Comment by plauche** [comment]
Thanks! I was actually able to work around this by following the instructions found in the `README.txt` in the root of the toolchain archive!
