### ISSUE TITLE
ncurses terminfo path

### ISSUE THREAD

**Issue by tpetazzoni** [bootlin/toolchains-builder#30]
The host ncurses in Buildroot forces /usr/share/terminfo as the location for terminfo data. However, Ubuntu installs the terminfo data in /lib/terminfo. Due to this, when running gdb, backspace doesn't work, unless one does export TERMINFO=/lib/terminfo/.

**Comment by crass** [comment]
I just got bit by this on a Debian 11 system. And the suggestion does indeed work. Another solution I found was to set `TERM=vt100` when running gdb. This seems fairly trivial to fix (if anything just have a wrapper script that checks which terminfo path should be set). Two years seems a long time for this to go unfixed. I guess there's not a lot of Debian/Ubuntu GDB buildroot users.

**Comment by tpetazzoni** [comment]
Turns out that this issue somehow resolved itself. I can reproduce it with the 2022.08-1 toolchains, but not the 2023.08-1 and later toolchains. It's not clear to me what fixed it, as "strace" doesn't show gdb searching into /lib/terminfo/. Is it perhaps ncurses having some built-in terminfo files now, as a fallback, or something like this? Anyway, it works now :-)
