### ISSUE TITLE
Still supported? Updates?

### ISSUE THREAD

**Issue by nimaim** [bootlin/toolchains-builder#31]
Hi Thomas :) Just wondering if these toolchains are still supported. Are you planning on any updates? I see the latest was built using BR 2018.11 base. As you know there has been loads of updates since: to GCC, standard C libs, etc. It's helped out a lot using these as an external toolchain for some of our builds (for debugging plus the overall quicker builds). Thanks.

**Comment by tpetazzoni** [comment]
Yes, I really want to ship updated toolchains soon, sorry for having been away from this project for too long. I hope to have toolchains based on 2020.02 in the not too distant future.

**Comment by nimaim** [comment]
No worries, thank you for the prompt reply. Hope you and your team are all well and safe! I will be on the lookout for the updated toolchains.

**Comment by tpetazzoni** [comment]
I have just pushed an updated version of all toolchains, based on Buildroot 2020.02. See also https://toolchains.bootlin.com/news.html
