### ISSUE TITLE
OpenMP

### ISSUE THREAD

**Issue by leezu** [bootlin/toolchains-builder#32]
Please provide OpenMP in the toolchains.
It would be great to provide it at least for linux-arm64, linux-armv5, linux-armv7, linux-mips, linux-s390x

For example, https://github.com/dockcross/dockcross/commit/78b49e90cb4ca6da575e6919867ce3ecbc80431c provides these.

**Comment by vfazio** [comment]
I think this can be closed. It looks like this has been enabled on newer builds?

**Comment by tpetazzoni** [comment]
Indeed, this has been enabled since commit 93f88ed30a4fd13ada7e2debf0d035855a690585.
