### ISSUE TITLE
Is it possible to add host tools to the SDK/ cross-tool chain ?

### ISSUE THREAD

**Issue by BhanuKiranChaluvadi** [bootlin/toolchains-builder#33]
Hi ,

I would like to add cmake, maven and python native support for the host machine along with the SDK ( build = host! = target). So the host system running the tool chain doesn't need to install cmake and python and all its dependencies so that the SDK is self-contained with all native packages and its dependencies ? These packages are need on the host machine but not on the target machine .

or Is there any current mechanism that allows to do it ?  The main reason for doing this is, i would like to distribute the SDK as a debian pacakge with self contained host utilities.

**Comment by tpetazzoni** [comment]
You can have a look at using Buildroot itself, which will allow you to build a SDK with as many host utilities as you want.
