### ISSUE TITLE
Document usage

### ISSUE THREAD

**Issue by kj7rrv** [bootlin/toolchains-builder#35]
Sorry if I just don't know what I'm doing, but could you please document usage? Do you copy it into /? Do you chroot in?

**Comment by tpetazzoni** [comment]
The toolchain-builders tools are not really meant to be used widely. They are used to produce the toolchains available at https://toolchains.bootlin.com/, which are really the "public" product that is meant to be used by everyone.

**Comment by biemster** [comment]
It's very possible @kj7rrv meant how to use the "public" product, since I'm wondering that now as well. My guess at the moment is just download + extract + set some PATHs, but it would be nice to have some instruction / confirmation on this for us people that do this very rarely?
