### ISSUE TITLE
musl 1.2.2 builds

### ISSUE THREAD

**Issue by MikeDombo** [bootlin/toolchains-builder#46]
https://musl.libc.org/releases.html

Musl 1.2.2 was released basically 1 year ago January 2021 with several fixes as well as CVE fixes. All the toolchains currently listed only use musl 1.2.0. 

Are there any plans to add musl 1.2.2? Anyway that I could help with such an effort or build it on my own?

**Comment by tpetazzoni** [comment]
Sorry for the delay, but we have now published 2021.11 toolchains, which have been completely updated, and they are based on musl 1.2.2. Thanks for your interest and patience!
