### ISSUE TITLE
The aarch64 toolchain (gcc 10.2) isn't working

### ISSUE THREAD

**Issue by sergey-suloev** [bootlin/toolchains-builder#48]
The aarch64 toolchain (gcc 10.2) isn't working
--------------------------------------------------------------------------------------

Running configuration tests
...
Checking for machine tuple... 
+ /home/sergey/Projects/armlinux/toolchains/bootlin/10/aarch64-buildroot-linux-gnu/bin/aarch64-buildroot-linux-gnu-g++ -dumpmachine
> aarch64-buildroot-linux-gnu
test config.qtbase.tests.machineTuple succeeded
Checking for valid makespec... 
+ cd /home/sergey/Projects/orpaltech/qt-build/qt5/build/linux-sun50i-a64-drm-g++/qtbase/config.tests/verifyspec && /home/sergey/Projects/orpaltech/qt-build/qt5/build/linux-sun50i-a64-drm-g++/qtbase/bin/qmake "CONFIG -= qt debug_and_release app_bundle lib_bundle" "CONFIG += shared warn_off console single_arch" "QMAKE_CFLAGS += --sysroot=/home/sergey/Projects/orpaltech/boards/nanopi-a64/sysroot" "QMAKE_CXXFLAGS += --sysroot=/home/sergey/Projects/orpaltech/boards/nanopi-a64/sysroot" "QMAKE_LFLAGS += --sysroot=/home/sergey/Projects/orpaltech/boards/nanopi-a64/sysroot" -early "CONFIG += cross_compile" /home/sergey/Projects/orpaltech/qt-build/qt5/qtbase/config.tests/verifyspec
> Info: creating stash file /home/sergey/Projects/orpaltech/qt-build/qt5/build/linux-sun50i-a64-drm-g++/qtbase/config.tests/.qmake.stash
+ cd /home/sergey/Projects/orpaltech/qt-build/qt5/build/linux-sun50i-a64-drm-g++/qtbase/config.tests/verifyspec && MAKEFLAGS= /usr/bin/make
> /home/sergey/Projects/armlinux/toolchains/bootlin/10/aarch64-buildroot-linux-gnu/bin/aarch64-buildroot-linux-gnu-g++ -c -pipe -march=armv8-a -mtune=cortex-a53 --sysroot=/home/sergey/Projects/orpaltech/boards/nanopi-a64/sysroot -O2 -w -fPIC  -I/home/sergey/Projects/orpaltech/qt-build/qt5/qtbase/config.tests/verifyspec -I. -I/home/sergey/Projects/orpaltech/qt-build/qt5/qtbase/mkspecs/devices/linux-sun50i-a64-drm-g++ -o verifyspec.o /home/sergey/Projects/orpaltech/qt-build/qt5/qtbase/config.tests/verifyspec/verifyspec.cpp
> /home/sergey/Projects/armlinux/toolchains/bootlin/10/aarch64-buildroot-linux-gnu/bin/aarch64-buildroot-linux-gnu-g++ --sysroot=/home/sergey/Projects/orpaltech/boards/nanopi-a64/sysroot -Wl,-O1 -Wl,-rpath-link,/home/sergey/Projects/orpaltech/boards/nanopi-a64/sysroot/usr/lib/aarch64-buildroot-linux-gnu -Wl,-rpath-link,/home/sergey/Projects/orpaltech/boards/nanopi-a64/sysroot/lib/aarch64-buildroot-linux-gnu -o verifyspec verifyspec.o     -lrt -lpthread -ldl -lz 
> /home/sergey/Projects/armlinux/toolchains/bootlin/10/aarch64-buildroot-linux-gnu/bin/../lib/gcc/aarch64-buildroot-linux-gnu/10.2.0/../../../../aarch64-buildroot-linux-gnu/bin/ld: cannot find crt1.o: No such file or directory
> /home/sergey/Projects/armlinux/toolchains/bootlin/10/aarch64-buildroot-linux-gnu/bin/../lib/gcc/aarch64-buildroot-linux-gnu/10.2.0/../../../../aarch64-buildroot-linux-gnu/bin/ld: cannot find crti.o: No such file or directory
> /home/sergey/Projects/armlinux/toolchains/bootlin/10/aarch64-buildroot-linux-gnu/bin/../lib/gcc/aarch64-buildroot-linux-gnu/10.2.0/../../../../aarch64-buildroot-linux-gnu/bin/ld: cannot find -lrt
> /home/sergey/Projects/armlinux/toolchains/bootlin/10/aarch64-buildroot-linux-gnu/bin/../lib/gcc/aarch64-buildroot-linux-gnu/10.2.0/../../../../aarch64-buildroot-linux-gnu/bin/ld: cannot find -lpthread
> /home/sergey/Projects/armlinux/toolchains/bootlin/10/aarch64-buildroot-linux-gnu/bin/../lib/gcc/aarch64-buildroot-linux-gnu/10.2.0/../../../../aarch64-buildroot-linux-gnu/bin/ld: cannot find -ldl
> /home/sergey/Projects/armlinux/toolchains/bootlin/10/aarch64-buildroot-linux-gnu/bin/../lib/gcc/aarch64-buildroot-linux-gnu/10.2.0/../../../../aarch64-buildroot-linux-gnu/bin/ld: cannot find -lz
> /home/sergey/Projects/armlinux/toolchains/bootlin/10/aarch64-buildroot-linux-gnu/bin/../lib/gcc/aarch64-buildroot-linux-gnu/10.2.0/../../../../aarch64-buildroot-linux-gnu/bin/ld: cannot find -lm
> collect2: error: ld returned 1 exit status
> make: *** [Makefile:68: verifyspec] Error 1
Note: Also available for Linux: linux-clang linux-icc

**Comment by sergey-suloev** [comment]
The libraries that it couldn't find were located in  /home/sergey/Projects/orpaltech/boards/nanopi-a64/sysroot/usr/lib/aarch64-linux-gnu  folder.

**Comment by tpetazzoni** [comment]
This doesn't seem to be related to the toolchain, but to how you are using it. You're using a custom sysroot, and not the original toolchain sysroot, so all sort of things can go wrong if your sysroot is incorrect. I'm afraid your bug report isn't a bug about the toochain being wrong, but your use of the toolchain being wrong. You would have the same problem with other toolchains.

**Comment by sergey-suloev** [comment]
@tpetazzoni   linaro 7.5 works fine. I just wanted to move to a newer gcc

**Comment by sergey-suloev** [comment]
@tpetazzoni  could you provide some documentation about using your toolchains ? they don't seem to be typical. For example, linaro toolchains always work with no issues.

**Comment by sergey-suloev** [comment]
I think I see where the issue is. it is looking into /home/sergey/Projects/orpaltech/boards/nanopi-a64/sysroot/lib/aarch64-buildroot-linux-gnu  for the libraries, but the default debian sysroot  has /lib/aarch64-linux-gnu.

**Comment by tpetazzoni** [comment]
They should work mostly like Linaro toolchains. If they don't, could you please provide step by step reproduction details, in a procedure that works with Linaro toolchains, but not Bootlin toolchains ? Thanks!
