### ISSUE TITLE
aclocal is broken for sparc64--glibc--stable-2021.11-1

### ISSUE THREAD

**Issue by crass** [bootlin/toolchains-builder#49]
When using the provided aclocal, I'm getting the following error message:

> Can't locate Automake/Config.pm in @INC (you may need to install the Automake::C
onfig module) (@INC contains: /builds/bootlin/toolchains-builder/build/sparc64--
glibc--stable-2021.11-1/share/automake-1.16 /etc/perl /usr/local/lib/x86_64-linu
x-gnu/perl/5.32.1 /usr/local/share/perl/5.32.1 /usr/lib/x86_64-linux-gnu/perl5/5
.32 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl-base /usr/lib/x86_64-linux-g
nu/perl/5.32 /usr/share/perl/5.32 /usr/local/lib/site_perl) at /usr/src/cross/sp
arc64--glibc--stable-2021.11-1/bin/aclocal-1.16 line 35.
BEGIN failed--compilation aborted at /usr/src/cross/sparc64--glibc--stable-2021.
11-1/bin/aclocal-1.16 line 35.

I can fix this by setting the envvar `PERL5LIB='/usr/src/cross/sparc64--glibc--stable-2021.11-1/share/automake-1.16'`, but then I run into this error:

> aclocal-1.16: error: couldn't open directory '/builds/bootlin/toolchains-builder/build/sparc64--glibc--stable-2021.11-1/share/aclocal-1.16': No such file or directory

I imagine if I moved the install to the path that it was originally built with it would work, but it would be nice if that weren't required. And I suspect that this issue exists for many if not all other builds, but I haven't checked.

**Comment by crass** [comment]
Somehow I missed `relocate-sdk.sh`. That fixed the issue.

**Comment by tpetazzoni** [comment]
Ideally, aclocal should not be part of the toolchain. The reason it is there is because Buildroot needs it to be the toolchain. But it should ideally be dropped from the toolchain tarball.

**Comment by crass** [comment]
Actually, wasn't wanting to use it, but it got used unexpectedly because I was putting the `bin` path at the start of `PATH`, so it was used instead of the system one. Upon further thought, it seems like it could be a good thing to include it to have a more complete package. In this case it would be nice to not have `relocate-sdk.sh`, but to have aclocal and others figure everything out via relative paths instead of the absolute paths they currently have.
