### ISSUE TITLE
Binutils 2.37 issue with bleeding-edge toolchain 2021.11-1

### ISSUE THREAD

**Issue by RomainNaour** [bootlin/toolchains-builder#51]
Hello,

The bleeding-edge toolchain 2021.11-1 fail to build qt5webengine due to an Binutils 2.37 issue.

See:
https://git.buildroot.net/buildroot/commit/?id=40f7b0bb6b91400b9e1fc60f410c9cdcbd1998ab

Prebuilt toolchains based on Binutils 2.37 must be rebuild with this fix.

**Comment by tpetazzoni** [comment]
The 2022.08 toolchains use binutils 2.38 (stable toolchain) or binutils 2.39 (bleeding-edge toolchain). We're about to release 2023.08 toolchains that use binutils 2.40 (stable toolchain) or binutils 2.41 (bleeding-edge toolchain).
