### ISSUE TITLE
GCC D cross-compiler 

### ISSUE THREAD

**Issue by wdlkmpx** [bootlin/toolchains-builder#53]
- https://github.com/buildroot/buildroot/commit/961de2062e6fa65b0dfa675e84570510664070bc
- https://github.com/buildroot/buildroot/blob/master/package/gcc/Config.in.host#L124
- https://en.m.wikipedia.org/wiki/D_(programming_language)

Supported in a few architectures, I think it does support more architectures. it may also work with musl, but requires glibc

It might be a good idea to add D to the toolchain, for educational purposes

Hmm this is the LLVM D compiler
https://github.com/ldc-developers/ldc/releases

**Comment by tpetazzoni** [comment]
We're no longer supporting building D language support in Buildroot, as it now requires a D compiler on the host to build the cross-compiler, and nobody did the work of addressing this issue in Buildroot. For what I see, the D language is very niche, and it is not widespread enough to justify it being supported in our toolchains. Of course, this sort of decision can always be revisited in the future if the situation changes.
