### ISSUE TITLE
2021.11-1: mips64-n32 issues with glibc > 34

### ISSUE THREAD

**Issue by ivoire** [bootlin/toolchains-builder#56]
An annoying bug has been found on glibc > v34: [#29069](https://sourceware.org/bugzilla/show_bug.cgi?id=29069).

Issue: 
* built a rootfs with the bootlin toolchain for mips64-n32 (2021.11-1)
* boot with qemu (`/usr/bin/qemu-system-mips64 -machine malta`)
* in the shell: `mkdir -m 777 -p /scratch` => `mkdir: cannot change permissions of '/scratch': Not a directory`

A fix has been backported to every versions (v34 and after) that fix the issue: [78fb88827362fbd2cc8aa32892ae5b015106e25c](https://sourceware.org/git/?p=glibc.git;a=commit;h=78fb88827362fbd2cc8aa32892ae5b015106e25c).

Rebuilding the 2021.11-1 toolchains with the updated glibc 34 would fix the issue.

**Comment by tpetazzoni** [comment]
Thanks for your bug report! The 2022.08 toolchains published last year use glibc 2.35, which I suppose as this issue fixed. We are about to publish 2023.08 toolchains that use glibc 2.37.
