### ISSUE TITLE
build-toolchain.sh doesn't flag all supported options

### ISSUE THREAD

**Issue by vfazio** [bootlin/toolchains-builder#60]
Currently, the generated fragments that are supposed to reflect the options that are enabled are overlooking BR2_GCC_ENABLE_OPENMP, BR2_TOOLCHAIN_BUILDROOT_DLANG, and possibly others.

https://github.com/bootlin/toolchains-builder/blob/master/build-toolchain.sh#L166

quick fix:

```
    if grep -q "BR2_GCC_ENABLE_OPENMP=y" ${configfile}; then
        echo "BR2_TOOLCHAIN_EXTERNAL_OPENMP=y" >> ${fragment_file}
    else
        echo "# BR2_TOOLCHAIN_EXTERNAL_OPENMP is not set" >> ${fragment_file}
    fi
    if grep -q "BR2_TOOLCHAIN_BUILDROOT_DLANG=y" ${configfile}; then
        echo "BR2_TOOLCHAIN_EXTERNAL_DLANG=y" >> ${fragment_file}
    else
        echo "# BR2_TOOLCHAIN_EXTERNAL_DLANG is not set" >> ${fragment_file}
    fi
```

**Comment by tpetazzoni** [comment]
Fixed by https://github.com/bootlin/toolchains-builder/commit/fe71b747edb2d86aff6356d163b0e8a60c4cd461
