### ISSUE TITLE
loongarch64: New architecture support needed

### ISSUE THREAD

**Issue by KatyushaScarlet** [bootlin/toolchains-builder#63]
loongarch64 is a new RISC architecture which has recently been supported by the open source community.
On :
* binutils 2.40
* gcc 12.1
* gdb 13.1
* glibc 2.36
* qemu 7.2.0

An overview of the development status of loongarch64 in the open source community can be seen here: https://areweloongyet.com/

**Comment by tpetazzoni** [comment]
Thanks for your request. However, toolchains-builder is based on Buildroot, and Buildroot does not have support for the Longarch64 architecture, and therefore toolchains-builder for now cannot build Longarch64 toolchains. If you're interested in Longarch64, I would recommend to contribute the support for this architecture to Buildroot. Then it will be easy for toolchains-builder to provide toolchains.
