### ISSUE TITLE
Newest toolchains build broken OpenBIOS firmwares

### ISSUE THREAD

**Issue by crass** [bootlin/toolchains-builder#64]
I've tried the two newest stable builds and the newest bleeding edge build and they all produce firmwares that cause QEMU to above. In contrast, the firmwares built with kernel.org toolchains work fine. For more details, see this OpenBIOS issue: openbios/openbios#15.

**Comment by tpetazzoni** [comment]
Thanks for your report. As reported https://github.com/openbios/openbios/issues/15, this is not an issue unique to Bootlin toolchains, it seems like it is an issue affecting other toolchains as well, so it's likely to be an upstream GCC or binutils issue. It's kind weird though that the toolchains at kernel.org are working well.

Could you try to narrow down if the same GCC version in kernel.org toolchains and Bootlin toolchains is working on one side, and broken on the other side ?

**Comment by tpetazzoni** [comment]
No feedback from the bug reporter, and probably not an issue with toolchains-builder, but more likely an upstream gcc/binutils issue.
