### ISSUE TITLE
How can I reproduce a build locally?

### ISSUE THREAD

**Issue by JonathanWilbur** [bootlin/toolchains-builder#66]
Can we view the pipelines somewhere to see what commands are executed, or is there some other way to reproduce a build of a toolchain locally?

**Comment by tpetazzoni** [comment]
Sure, let's say you want to rebuild the AArch64 glibc bleeding edge toolchain, version 2023.11. Head to https://toolchains.bootlin.com/downloads/releases/toolchains/aarch64/readmes/aarch64--glibc--bleeding-edge-2023.11-1.txt, which has all the instructions to do so!

**Comment by tpetazzoni** [comment]
Of course, similar readme files exist for all toolchains, just navigate in https://toolchains.bootlin.com/downloads/releases/toolchains/, chose your architecture, and go in the readmes subfolder.

**Comment by JonathanWilbur** [comment]
Very cool. Thank you!
