### ISSUE TITLE
No LLVM? No Zig? No Clang?

### ISSUE THREAD

**Issue by xplshn** [bootlin/toolchains-builder#67]

**Comment by xplshn** [comment]
By Zig I meant their drop-in replacement for Clang, which is `zig c` and `zig c++`
I didn't mean zig the language. See this if interested in adding Zig: https://ziglang.org/#:~:text=Incrementally%20improve%20your%20C/C++/Zig%20codebase.,LTO%20is%20enabled%20by%20default.

Zig supports crosscompilation out of the box and comes with many utilities necessary to build programs as built-ins

Highlighted part of the Zig Manpage: https://manned.org/zig.1#:~:text=ar%20%20%20%20%20Use%20Zig%20as%20a,Zig%20as%20a%20drop%2Din%20ranlib

[After all, clang is just a "driver" for the LLVM backend.](https://manned.org/clang#:~:text=Driver%20The%20clang%20executable%20is,to%20run%20the%20other%20tools.)

**Comment by tpetazzoni** [comment]
toolchain-builder uses Buildroot to build the toolchain. Buildroot currently does not have support to build a LLVM/Clang toolchain nor Zig. So currently, this request cannot be fulfilled, we would need first to get Buildroot support for those features.
