### ISSUE TITLE
libcrypt is not included in armv7-eabihf--glibc--bleeding-edge-2024.02-1

### ISSUE THREAD

**Issue by cetehem** [bootlin/toolchains-builder#70]
Is it a bug ?
Is it a feature ?

libcrypt **not included** in armv7-eabihf--glibc--bleeding-edge-2024.02-1 :
```
$ cd /opt/x-tools/20240201/armv7-eabihf--glibc--bleeding-edge-2024.02-1 
$ find . -name "libcrypt*" -o -name "crypt.h"
$
```
libcrypt **included** In armv7-eabihf--glibc--bleeding-edge-2023.11-1 ( and some other too )
```
$ /opt/x-tools/20231101/armv7-eabihf--glibc--bleeding-edge-2023.11-1
$ find . -name "libcrypt*" -o -name "crypt.h"
./arm-buildroot-linux-gnueabihf/sysroot/lib/libcrypt.so.1
./arm-buildroot-linux-gnueabihf/sysroot/usr/include/crypt.h
./arm-buildroot-linux-gnueabihf/sysroot/usr/lib/libcrypt.so
./arm-buildroot-linux-gnueabihf/sysroot/usr/lib/libcrypt.a
$
```

Thanks
Bruno

**Comment by tpetazzoni** [comment]
This is expected. Indeed in 2023.11 we were using glibc 2.38, and in 2024.02 we have updated to glibc 2.39. And glibc 2.39 has decided to drop libcrypt. See the release notes at https://lists.gnu.org/archive/html/info-gnu/2024-01/msg00017.html.

The replacement is to use the separate libxcrypt library, which is API compatible, available at https://github.com/besser82/libxcrypt/

**Comment by cetehem** [comment]
So, it's a feature !
Thanks for this fast answer
